defmodule Faker.Tolkien.En do
  import Faker, only: [sampler: 2]

  @moduledoc """
  Functions for generating J.R.R Tolkien legendarium data in English.
  """

  @doc """
  Returns a random J.R.R. Tolkien race in English

  ## Examples

      iex> Faker.Tolkien.race()
      "Uruk-hai"
      iex> Faker.Tolkien.race()
      "Trolls"
      iex> Faker.Tolkien.race()
      "Half-trolls"
      iex> Faker.Tolkien.race()
      "Vampire"
  """
  @spec race() :: String.t()
  sampler(:race, [
    "Ainur",
    "Balrogs",
    "Barrow-wights",
    "Beorning",
    "Children of Ilúvatar",
    "Demons",
    "Dragons",
    "Dwarves",
    "Elves",
    "Ents",
    "Fairies",
    "Giants",
    "Goblins",
    "Half-elven",
    "Half-orc",
    "Half-trolls",
    "Hobbits",
    "Huorns",
    "Kaukareldar",
    "Lintips",
    "Maiar",
    "Mens",
    "Mewlips",
    "Oarni",
    "Ogres",
    "Orcs",
    "Shape Shifters",
    "Skin-changer",
    "Spiders",
    "Trolls",
    "Uruk-hai",
    "Valar",
    "Vampire",
    "Wargs",
    "Werewolves",
    "Wraiths"
  ])

  @doc """
  Returns a random J.R.R. Tolkien poem name in English

  ## Examples

      iex> Faker.Tolkien.poem()
      "A Elbereth Gilthoniel"
      iex> Faker.Tolkien.poem()
      "The Road Goes Ever On and On"
      iex> Faker.Tolkien.poem()
      "Arise, arise, Riders of Theoden!"
      iex> Faker.Tolkien.poem()
      "A Rhyme of Lore"
  """
  @spec poem() :: String.t()
  sampler(:poem, [
    "Chip the glasses and crack the plates",
    "Far over the misty mountains cold",
    "O! What are you doing?",
    "Clap! Snap! The black crack!",
    "Fifteen birds in five fir trees",
    "The wind was on the withered heath",
    "Old fat spider spinning in a tree!",
    "Roll-Roll-Roll-Roll",
    "The King beneath the mountains",
    "Under the mountain dark and tall",
    "The dragon is withered",
    "Sing all ye joyful!",
    "Roads go ever, ever on",
    "The Road Goes Ever On and On",
    "Three Rings for the Elven-Kings Under the Sky",
    "A Walking Song",
    "Snow-white! Snow-white! O Lady Clear!",
    "Ho! Ho! Ho! To the Bottle I Go",
    "The Bath Song",
    "Farewell We Call to Hearth and Hall!",
    "O! Wanderers in the Shadowed Land",
    "Hey dol! merry dol! ring a dong dillo!",
    "Hop along, my little friends, up the Withywindle!",
    "O slender as a willow-wand!",
    "'I Had An Errand There: Gathering Water-Lilies'",
    "Ho! Tom Bombadil, Tom Bombadillo!",
    "Cold Be Hand and Heart and Bone",
    "Get Out! You old Wight! Vanish in the Sunlight!",
    "Wake Now My Merry Lads! Wake and Hear Me Calling!",
    "Hey! Now! Come Hoy Now! Whither Do You Wander?",
    "The Man in the Moon Stayed Up Too Late",
    "All That Is Gold Does Not Glitter",
    "The Fall of Gil-galad",
    "Song of Beren and Lúthien",
    "The Stone Troll",
    "Eärendil was a mariner",
    "A Elbereth Gilthoniel",
    "Seek for the Sword that was broken",
    "When winter first begins to bite",
    "I sit beside the fire and think",
    "The world was young, the mountains green",
    "An Elven-maid there was of old",
    "When evening in the Shire was grey",
    "I sang of leaves, of leaves of gold (Galadriel's Song of Eldamar)",
    "Ai! laurië lantar lassi súrinen (Namárië)",
    "Through Rohan Over Fen and Field Where the Long Grass Grows",
    "Gondor! Gondor, between the Mountains and the Sea!",
    "Arise now, arise, Riders of Theoden!",
    "Learn now the lore of Living Creatures!",
    "In The Willow-meads Of Tasarinan",
    "When Spring unfolds the beechen leaf, and sap is in the bough",
    "O Orofarne Lassemista, Carnimirie!",
    "We come, we come with roll of drum",
    "Where now are the Dunedain, Elessar, Elessar?",
    "Where now the horse and the rider?",
    "In Dwimordene, in Lorien",
    "Ere iron was found or tree was hewn",
    "Long List of the Ents",
    "A Rhyme of Lore",
    "The cold hard lands",
    "Oliphaunt",
    "Over the land there lies a long shadow",
    "From dark Dunharrow in the dim morning",
    "Arise, arise, Riders of Theoden!",
    "Song of the Mounds of Mundburg",
    "When the black breath blows",
    "Silver flow the streams from Celos to Erui",
    "In western lands beneath the Sun",
    "Long live the Halflings! Praise them with great praise!",
    "To the Sea, to the Sea! The white gulls are crying",
    "Sing now, ye people of the Tower of Anor",
    "Out of doubt, out of dark, to the day’s rising",
    "The Road goes ever on and on",
    "Still around the corner there may wait"
  ])

  @doc """
  Returns a random J.R.R. Tolkien name in English

  ## Examples

      iex> Faker.Tolkien.name()
      "Tar-Amandil"
      iex> Faker.Tolkien.name()
      "Saradas Brandybuck"
      iex> Faker.Tolkien.name()
      "Reginard Took"
      iex> Faker.Tolkien.name()
      "Bereg"
  """
  @spec name() :: String.t()
  sampler(:name, [
    "Adalbert Bolger",
    "Adaldrida Bolger",
    "Adalgar Bolger",
    "Adalgrim Took",
    "Adam Hornblower",
    "Adamanta Chubb",
    "Adanel",
    "Adelard Took",
    "Adrahil",
    "Aegnor",
    "Aerin",
    "Agathor",
    "Aghan",
    "Aglahad",
    "Ailinel",
    "Aldamir",
    "Aldor",
    "Alfrida of the Yale",
    "Algund",
    "Almarian",
    "Almáriel",
    "Almiel",
    "Alphros",
    "Amandil",
    "Amaranth Brandybuck",
    "Amarië",
    "Amdír",
    "Amethyst Hornblower",
    "Amlach",
    "Amlaith",
    "Amras",
    "Amrod",
    "Amroth",
    "Amrothos",
    "Anairë",
    "Anardil",
    "Anborn",
    "Ancalagon",
    "Andreth",
    "Andróg",
    "Andvír",
    "Andwise Roper",
    "Angamaitë",
    "Angbor",
    "Angelica Baggins",
    "Angelimir",
    "Angrim",
    "Angrod",
    "Annael",
    "Anson Roper",
    "Ar-Adûnakhôr",
    "Ar-Gimilzôr",
    "Ar-Pharazôn",
    "Ar-Sakalthôr",
    "Ar-Zimrathôn",
    "Arachon",
    "Arador",
    "Araglas",
    "Aragorn",
    "Aragost",
    "Arahad",
    "Arahael",
    "Aranarth",
    "Arantar",
    "Aranuir",
    "Aranwë",
    "Araphant",
    "Araphor",
    "Arassuil",
    "Aratan",
    "Arathorn",
    "Araval",
    "Aravir",
    "Aravorn",
    "Arciryas",
    "Ardamir",
    "Aredhel",
    "Argeleb",
    "Argon",
    "Argonui",
    "Arminas",
    "Artamir",
    "Arthad",
    "Arvedui",
    "Arvegil",
    "Arveleg",
    "Arwen",
    "Arwen Evenstar",
    "Asgon",
    "Asphodel Brandybuck",
    "Atanalcar",
    "Atanatar",
    "Aulendil",
    "Avranc",
    "Axantur",
    "Azaghâl",
    "Azog",
    "Bain",
    "Balbo Baggins",
    "Baldor",
    "Balin",
    "Ban",
    "Bandobras Took",
    "Barach",
    "Baragund",
    "Barahir",
    "Baran",
    "Baranor",
    "Bard",
    "Bard the Bowman",
    "Barliman Butterbur",
    "Basso Boffin",
    "Beechbone",
    "Belba Baggins",
    "Beldir",
    "Beldis",
    "Belecthor",
    "Beleg",
    "Belegor",
    "Belegorn",
    "Belegund",
    "Belemir",
    "Belen",
    "Beleth",
    "Bell Goodchild",
    "Belladonna Took",
    "Bëor",
    "Beorn",
    "Bereg",
    "Beregar",
    "Beregond",
    "Berelach",
    "Beren",
    "Bergil",
    "Beril",
    "Berilac Brandybuck",
    "Bert",
    "Berúthiel",
    "Berylla Boffin",
    "Bifur",
    "Bilbo Baggins",
    "Bilbo Gardner",
    "Bill Butcher",
    "Bill Ferny",
    "Bill Huggins",
    "Bingo Baggins",
    "Blanco Bracegirdle",
    "Blodren",
    "Boar of Everholt",
    "Bodo Proudfoot",
    "Bodruith",
    "Bofur",
    "Bolg",
    "Bombur",
    "Bór",
    "Borin",
    "Borlach",
    "Borlad",
    "Borlas",
    "Boromir",
    "Boron",
    "Borondir",
    "Borthand",
    "Bosco Boffin",
    "Bowman Cotton",
    "Brand",
    "Brandir",
    "Bregil",
    "Brego",
    "Bregolas",
    "Bregor",
    "Briffo Boffin",
    "Brodda",
    "Bruno Bracegirdle",
    "Brytta",
    "Bucca of the Marish",
    "Buffo Boffin",
    "Buldar",
    "Bullroarer Took",
    "Bungo Baggins",
    "Calimehtar",
    "Calimmacil",
    "Caliondo",
    "Calmacil",
    "Camellia Sackville",
    "Caranthir",
    "Carc",
    "Carcharoth",
    "Carl Cotton",
    "Castamir",
    "Celeborn",
    "Celebrían",
    "Celebrimbor",
    "Celebrindor",
    "Celegorm",
    "Celepharn",
    "Cemendur",
    "Ceorl",
    "Chica Chubb",
    "Círdan",
    "Cirion",
    "Ciryandil",
    "Ciryatur",
    "Ciryon",
    "Cora Goodbody",
    "Cotman",
    "Cottar",
    "Curufin",
    "Daddy Twofoot",
    "Daeron",
    "Dagnir",
    "Dáin Ironfoot",
    "Dairuin",
    "Daisy Baggins",
    "Daisy Gamgee",
    "Daisy Gardner",
    "Damrod",
    "Denethor",
    "Déor",
    "Déorwine",
    "Dernhelm",
    "Derufin",
    "Dervorin",
    "Diamond of Long Cleeve",
    "Dina Diggle",
    "Dinodas Brandybuck",
    "Dior",
    "Dírhael",
    "Dírhaval",
    "Dís",
    "Doderic Brandybuck",
    "Dodinas Brandybuck",
    "Donnamira Took",
    "Dora Baggins",
    "Dori",
    "Dorlas",
    "Draugluin",
    "Drogo Baggins",
    "Druda Burrows",
    "Dudo Baggins",
    "Duilin",
    "Duinhir",
    "Dúnhere",
    "Durin",
    "Durin's Bane",
    "Dwalin",
    "Eärendil",
    "Eärendur",
    "Eärnil",
    "Eärnur",
    "Eärwen",
    "Ebor",
    "Ecthelion",
    "Edrahil",
    "Egalmoth",
    "Eglantine Banks",
    "Eilinel",
    "Elanor Gardner",
    "Elatan",
    "Elboron",
    "Eldacar",
    "Eldalótë",
    "Eldarion",
    "Elemmakil",
    "Elemmírë",
    "Elendil",
    "Elendur",
    "Elentir",
    "Elenwë",
    "Elfhelm",
    "Elfhild",
    "Elfstan Fairbairn",
    "Elfwine",
    "Elladan",
    "Elmar",
    "Elmo",
    "Elphir",
    "Elrohir",
    "Elrond",
    "Elros",
    "Elulindo",
    "Eluréd",
    "Elurín",
    "Elwing",
    "Emeldir",
    "Enel",
    "Enelyë",
    "Enerdhil",
    "Enthor",
    "Eofor",
    "Eöl",
    "Éomer",
    "Éomund",
    "Eorl",
    "Éothain",
    "Éothéod",
    "Éowyn",
    "Eradan",
    "Erchirion",
    "Erendis",
    "Erestor",
    "Erien",
    "Erkenbrand",
    "Erling",
    "Esmeralda Took",
    "Estella Bolger",
    "Estelmo",
    "Everard Took",
    "Falco Chubb-Baggins",
    "Faniel",
    "Faramir",
    "Faramir Took",
    "Farin",
    "Farmer Cotton",
    "Farmer Maggot",
    "Fastolph Bolger",
    "Fastred",
    "Fastred of Greenholm",
    "Fëanor",
    "Fengel",
    "Ferdibrand Took",
    "Ferdinand Took",
    "Ferumbras Took",
    "Fíli",
    "Filibert Bolger",
    "Fimbrethil",
    "Finarfin",
    "Finbor",
    "Findegil",
    "Findis",
    "Finduilas",
    "Fingolfin",
    "Fingon",
    "Finrod",
    "Finwë",
    "Fíriel",
    "Fíriel Fairbairn",
    "Flambard Took",
    "Flói",
    "Folca",
    "Folco Boffin",
    "Folco Burrowes",
    "Folcred",
    "Folcwine",
    "Forhend",
    "Forlong",
    "Forthwini",
    "Fortinbras Took",
    "Forweg",
    "Fosco Baggins",
    "Fram",
    "Frár",
    "Fréa",
    "Fréaláf",
    "Fréawine",
    "Freca",
    "Fredegar Bolger",
    "Frerin",
    "Frodo Baggins",
    "Frodo Gardner",
    "Frór",
    "Frumgar",
    "Fundin",
    "Gaffer Gamgee",
    "Galadhon",
    "Galador",
    "Galadriel",
    "Galathil",
    "Galdor",
    "Galdor of the Havens",
    "Galion",
    "Gálmód",
    "Gamil Zirak",
    "Gamling",
    "Gandalf",
    "Gandalf the Grey",
    "Gandalf the White",
    "Gárulf",
    "Gelmir",
    "Gerda Boffin",
    "Gerontius Took",
    "Gethron",
    "Ghân-buri-Ghân",
    "Gil-galad",
    "Gilbarad",
    "Gildis",
    "Gildor",
    "Gilly Brownlock",
    "Gilmith",
    "Gilraen",
    "Gilwen",
    "Gimilkhâd",
    "Gimilzagar",
    "Gimli",
    "Girion",
    "Glaurung",
    "Gléowine",
    "Glirhuin",
    "Glóin",
    "Glóredhel",
    "Glorfindel",
    "Golasgil",
    "Goldberry",
    "Goldilocks Gardner",
    "Goldwine",
    "Golfimbul",
    "Gollum",
    "Gorbadoc Brandybuck",
    "Gorbulas Brandybuck",
    "Gorgol",
    "Gorhendad Oldbuck",
    "Gorlim",
    "Gormadoc Brandybuck",
    "Gothmog",
    "Gram",
    "Great Eagle",
    "Great Goblin",
    "Griffo Boffin",
    "Grim",
    "Gríma",
    "Grìma Wormtongue",
    "Grimbeorn",
    "Grimbold",
    "Grishnákh",
    "Grithnir",
    "Gróin",
    "Grór",
    "Gruffo Boffin",
    "Guilin",
    "Gundabald Bolger",
    "Gundahad Bolger",
    "Gundahar Bolger",
    "Gundolpho Bolger",
    "Gundor",
    "Guthláf",
    "Gwaihir",
    "Gwindor",
    "Hador",
    "Halbarad",
    "Haldad",
    "Haldan",
    "Haldar",
    "Haldir",
    "Haleth",
    "Halfast Gamgee",
    "Halfred Gamgee",
    "Halfred Greenhand",
    "Halfred of Overhill",
    "Hallacar",
    "Hallas",
    "Hallatan",
    "Halmir",
    "Háma",
    "Hamfast Gardner",
    "Hamfast of Gamwich",
    "Hamson Gamgee",
    "Handir",
    "Hanna Goldworthy",
    "Hannar",
    "Hardang",
    "Harding",
    "Harding of the Hill",
    "Hareth",
    "Harry Goatleaf",
    "Hathaldir",
    "Hathol",
    "Hatholdir",
    "Hazad",
    "Helm",
    "Henderch",
    "Hending",
    "Herefara",
    "Herendil",
    "Heribald Bolger",
    "Herion",
    "Herubrand",
    "Herugar Bolger",
    "Herumor",
    "Hild",
    "Hilda Bracegirdle",
    "Hildibrand Took",
    "Hildifons Took",
    "Hildigard Took",
    "Hildigrim Took",
    "Hirgon",
    "Hiril",
    "Hirluin",
    "Hirwen",
    "Hob Gammidge",
    "Hob Hayward",
    "Hobson",
    "Holdwine",
    "Holfast Gardner",
    "Holman Cotton",
    "Horn",
    "Huan",
    "Hugo Boffin",
    "Hugo Bracegirdle",
    "Hundad",
    "Hundar",
    "Hunleth",
    "Hunthor",
    "Huor",
    "Húrin",
    "Hyarmendacil",
    "Iago Grubb",
    "Îbal",
    "Ibun",
    "Idis",
    "Idril",
    "Ilberic Brandybuck",
    "Imin",
    "Iminyë",
    "Imlach",
    "Imrahil",
    "Imrazôr",
    "Indis",
    "Indor",
    "Ingold",
    "Ingwë",
    "Ingwion",
    "Inziladûn",
    "Inzilbêth",
    "Ioreth",
    "Iorlas",
    "Írildë",
    "Írimë",
    "Írimon",
    "Irolas",
    "Isembard Took",
    "Isembold Took",
    "Isengar Took",
    "Isengrim",
    "Isildur",
    "Isilmë",
    "Isilmo",
    "Isumbras",
    "Ithilbor",
    "Ivorwen",
    "Ivriniel",
    "Ivy Goodenough",
    "Jago Boffin",
    "Jessamine Boffin",
    "Khamûl",
    "Khîm",
    "Kíli",
    "King of the Dead",
    "Lagduf",
    "Lalaith",
    "Landroval",
    "Largo Baggins",
    "Larnach",
    "Laura Grubb",
    "Lavender Grubb",
    "Leaflock",
    "Legolas",
    "Lenwë",
    "Léod",
    "Lily Baggins",
    "Lily Brown",
    "Linda Baggins",
    "Lindir",
    "Lindissë",
    "Lindórië",
    "Lobelia Sackville-Baggins",
    "Lofar",
    "Lonely Troll",
    "Longo Baggins",
    "Lóni",
    "Lorgan",
    "Lothíriel",
    "Lotho Sackville-Baggins",
    "Lugdush",
    "Lúthien",
    "Mablung",
    "Madoc Brandybuck",
    "Madril",
    "Maedhros",
    "Maeglin",
    "Maglor",
    "Magor",
    "Mahtan",
    "Mairen",
    "Malach",
    "Malantur",
    "Malbeth",
    "Mallor",
    "Malva Headstrong",
    "Malvegil",
    "Manthor",
    "Manwendil",
    "Marach",
    "Marcho",
    "Mardil",
    "Marhari",
    "Marhwini",
    "Marigold Gamgee",
    "Marmadas Brandybuck",
    "Marmadoc Brandybuck",
    "Marroc Brandybuck",
    "Mat Heathertoes",
    "Mauhúr",
    "May Gamgee",
    "Meleth",
    "Melian",
    "Melilot Brandybuck",
    "Menegilda Goold",
    "Meneldil",
    "Meneldor",
    "Mentha Brandybuck",
    "Meriadoc Brandybuck",
    "Merimac Brandybuck",
    "Merimas Brandybuck",
    "Merry Gardner",
    "Milo Burrows",
    "Mîm",
    "Mimosa Bunce",
    "Minardil",
    "Minastan",
    "Minohtar",
    "Minto Burrows",
    "Mirabella Took",
    "Míriel",
    "Mithrellas",
    "Mogru",
    "Moro Burrows",
    "Morwë",
    "Morwen",
    "Morwen Steelsheen",
    "Mosco Burrows",
    "Mouth of Sauron",
    "Mrs. Bunce",
    "Mrs. Maggot",
    "Mungo Baggins",
    "Muzgash",
    "Myrtle Burrows",
    "Náin",
    "Náli",
    "Nár",
    "Narmacil",
    "Narvi",
    "Nazgûl",
    "Nellas",
    "Nerdanel",
    "Nessanië",
    "Nienor",
    "Nimloth of Doriath",
    "Nimrodel",
    "Nina Lightfoot",
    "Nob",
    "Nolondil",
    "Nora Bolger",
    "Nori",
    "Númendil",
    "Núneth",
    "Nurwë",
    "Odo Proudfoot",
    "Odovacar Bolger",
    "Ohtar",
    "Óin",
    "Old Noakes",
    "Olo Proudfoot",
    "Olwë",
    "Ondoher",
    "Orchaldor",
    "Orgulas Brandybuck",
    "Ori",
    "Orleg",
    "Ornendil",
    "Ornil",
    "Orodreth",
    "Oromendil",
    "Orontor",
    "Oropher",
    "Orophin",
    "Ostoher",
    "Otho Sackville-Baggins",
    "Othrondir",
    "Otto Boffin",
    "Paladin Took",
    "Pansy Baggins",
    "Peeping Jack",
    "Pelendur",
    "Pengolodh",
    "Peony Baggins",
    "Peregrin Took",
    "Pervinca Took",
    "Pimpernel Took",
    "Pippin Gardner",
    "Poldor",
    "Polo Baggins",
    "Ponto Baggins",
    "Poppy Chubb-Baggins",
    "Porto Baggins",
    "Posco Baggins",
    "Pott the Mayor",
    "Primrose Boffin",
    "Primrose Gardner",
    "Primula Brandybuck",
    "Prisca Baggins",
    "Quennar",
    "Quickbeam",
    "Radagast",
    "Radbug",
    "Radhruin",
    "Ragnir",
    "Ragnor",
    "Reginard Took",
    "Rían",
    "Roäc",
    "Robin Gardner",
    "Robin Smallburrow",
    "Rollo Boffin",
    "Rómendacil",
    "Rorimac Brandybuck",
    "Rosa Baggins",
    "Rosamunda Took",
    "Rose Cotton",
    "Rose Gardner",
    "Rowan",
    "Rowlie Appledore",
    "Ruby Bolger",
    "Ruby Gardner",
    "Rudibert Bolger",
    "Rudigar Bolger",
    "Rudolph Bolger",
    "Rufus Burrows",
    "Rúmil",
    "Sador",
    "Saelon",
    "Saeros",
    "Sagroth",
    "Salvia Brandybuck",
    "Samwise Gamgee",
    "Sancho Proudfoot",
    "Sangahyando",
    "Sapphira Brockhouse",
    "Saradas Brandybuck",
    "Saradoc Brandybuck",
    "Saruman",
    "Saruman the White",
    "Sauron",
    "Scatha",
    "Seredic Brandybuck",
    "Shadowfax",
    "Shagram",
    "Shelob",
    "Sigismond Took",
    "Silmariën",
    "Siriondil",
    "Skinbark",
    "Smaug",
    "Snaga",
    "Soronto",
    "Tal-Elmar",
    "Tanta Hornblower",
    "Tar-Alcarin",
    "Tar-Aldarion",
    "Tar-Amandil",
    "Tar-Anárion",
    "Tar-Ancalimë",
    "Tar-Ancalimon",
    "Tar-Anducal",
    "Tar-Ardamin",
    "Tar-Atanamir",
    "Tar-Calmacil",
    "Tar-Ciryatan",
    "Tar-Elendil",
    "Tar-Meneldur",
    "Tar-Minastir",
    "Tar-Míriel",
    "Tar-Palantir",
    "Tar-Súrion",
    "Tar-Telemmaitë",
    "Tar-Telperiën",
    "Tar-Vanimeldë",
    "Tarannon Falastur",
    "Tarcil",
    "Tarciryan",
    "Targon",
    "Tarondor",
    "Tata",
    "Tatië",
    "Ted Sandyman",
    "Telchar",
    "Telemnar",
    "Telumehtar Umbardacil",
    "The Great Goblin",
    "The Lord of the Eagles",
    "The Necromancer",
    "Thengel",
    "Theobald Bolger",
    "Théoden",
    "Théodred",
    "Théodwyn",
    "Thingol",
    "Thorin",
    "Thorin Oakenshield",
    "Thorin Stonehelm",
    "Thorondir",
    "Thorondor",
    "Thráin",
    "Thranduil",
    "Thrór",
    "Tindómiel",
    "Tobold Hornblower",
    "Togo Goodbody",
    "Tolman Cotton Junior",
    "Tolman Gardner",
    "Tom Bombadil",
    "Tom Pickthorn",
    "Torhir Ifant",
    "Tosto Boffin",
    "Treebeard",
    "Tuor",
    "Turambar",
    "Turgon",
    "Túrin",
    "Uffo Boffin",
    "Ufthak",
    "Ulbar",
    "Uldor",
    "Ulfang",
    "Ulfast",
    "Ulrad",
    "Ulwarth",
    "Ungoliant",
    "Urthel",
    "Valacar",
    "Valandil",
    "Valandur",
    "Vardamir",
    "Vardilmë",
    "Vëantur",
    "Vidugavia",
    "Vidumavi",
    "Vigo Boffin",
    "Vinitharya",
    "Vorondil",
    "Voronwë",
    "Walda",
    "Watcher in the Water",
    "Wídfara",
    "Wilcome",
    "Wilibald Bolger",
    "Wilimar Bolger",
    "Will Whitfoot",
    "William",
    "Willie Banks",
    "Wiseman Gamwich",
    "Witch-king",
    "Wulf",
    "Yávien",
    "Zamîn",
    "Zimrahin",
    "Zimraphel"
  ])

  @doc """
  Returns a random J.R.R. Tolkien location in English

  ## Examples

      iex> Faker.Tolkien.location()
      "Bree-land"
      iex> Faker.Tolkien.location()
      "Buckland"
      iex> Faker.Tolkien.location()
      "River of Aros"
      iex> Faker.Tolkien.location()
      "Dimrill Gate"
  """
  @spec location() :: String.t()
  sampler(:location, [
    "Abyss",
    "Achad Tarlang",
    "Adorn",
    "Adurant",
    "Aelin-uial",
    "Afros",
    "Agar",
    "Agathurush",
    "Aglarond",
    "Akallabêth",
    "Aldalómë",
    "Aldburg",
    "Alqualondë",
    "Aman",
    "Ambaróna",
    "Amon Amarth",
    "Amon Anwar",
    "Amon Darthir",
    "Amon Dîn",
    "Amon Ereb",
    "Amon Ethir",
    "Amon Gwareth",
    "Amon Hen",
    "Amon Lanc",
    "Amon Lhaw",
    "Amon Obel",
    "Amon Rûdh",
    "Amon Sûl",
    "Amon Uilos",
    "Anadûnê",
    "Ancient West",
    "Andafalassë",
    "Andor",
    "Andram",
    "Andrast",
    "Andrath",
    "Andúne Pelo",
    "Andúnië",
    "Andustar",
    "Anfalas",
    "Anfauglith",
    "Angamando",
    "Angband",
    "Anghabar",
    "Angren",
    "Angrenost",
    "Annon-in-Gelydh",
    "Annúminas",
    "Anórien",
    "Antaro",
    "Araman",
    "Arandor",
    "Archet",
    "Ard-galen",
    "Arda",
    "Argonath",
    "Armenelos",
    "Arnach",
    "Arnor",
    "Arossiach",
    "Arthedain",
    "Arthor na Challonnas",
    "Arthor na Forlonnas",
    "Arthórien",
    "Arvernien",
    "Ash Mountains",
    "Astulat",
    "Atalantë",
    "Athrad Angren",
    "Avallónë",
    "Avathar",
    "Azanulbizar",
    "Bag End",
    "Bag-End",
    "Bagshot Row",
    "Balar",
    "Bamfurlong",
    "Bandushathûr",
    "Bar-en-Danwedh",
    "Bar-en-Nibin-noeg",
    "Bar-erib",
    "Bar-in-Mŷl",
    "Barad Eithel",
    "Barad Nimras",
    "Barad-dûr",
    "Baranduin",
    "Barazinbar",
    "Barrow-downs",
    "Barrowfield",
    "Battle Pit",
    "Battle Plain",
    "Bay of Andúnië",
    "Bay of Balar",
    "Bay of Belfalas",
    "Bay of Eldamar",
    "Bay of Eldanna",
    "Bay of Rómenna",
    "Belegaer",
    "Belegost",
    "Beleriand",
    "Belfalas",
    "Bent Seas",
    "Beorn's Hall",
    "Beorn's House",
    "Bindbale Wood",
    "Birchwoods of Nimbrethil",
    "Black Crack",
    "Black Gate",
    "Black Land",
    "Black Pit",
    "Black Pits",
    "Blackroot",
    "Blessed Realm",
    "Blue Mountains",
    "Bombadil's House",
    "Bonfire Glade",
    "Bony ridge",
    "Branda-nîn",
    "Brandywine Bridge",
    "Bree Hill",
    "Bree-land",
    "Bree",
    "Breredon",
    "Brethil",
    "Bridge of Esgalduin",
    "Bridge of Khazad-dûm",
    "Bridge of Mitheithel",
    "Bridge of Stonebows",
    "Bridgefields",
    "Brilthor",
    "Brithiach",
    "Brithombar",
    "Brithon",
    "Brockenbores",
    "Brodda's hall",
    "Brown Lands",
    "Bruinen",
    "Buck Hill",
    "Buckland Gate",
    "Buckland Road",
    "Buckland",
    "Bucklebury Ferry",
    "Bucklebury Ford",
    "Bucklebury",
    "Budge Ford",
    "Budgeford",
    "Bundushathûr",
    "Bywater Pool",
    "Bywater Road",
    "Bywater",
    "Cabed-en-Aras",
    "Cair Andros",
    "Calacirian",
    "Calacirya",
    "Calembel",
    "Calenardhon",
    "Calenhad",
    "Calmindon",
    "Cape Balar",
    "Cape of Andrast",
    "Cape of Forochel",
    "Carach Angren",
    "Caradhras",
    "Caragdûr",
    "Caras Galadhon",
    "Carchost",
    "Cardolan",
    "Carn Dûm",
    "Carnen",
    "Carrock",
    "Causeway Forts",
    "Caverns of Helm's Deep",
    "Caverns of Narog",
    "Caverns of the Oaritsi",
    "Caves of Androth",
    "Caves of Menegroth",
    "Celduin",
    "Celebdil",
    "Celebrant",
    "Celebros",
    "Celon",
    "Celos",
    "Central Highlands",
    "Cerin Amroth",
    "Chamber of Mazarbul",
    "Chambers of Fire",
    "Chetwood",
    "Chill Gulf",
    "Ciril",
    "Cirith Dúath",
    "Cirith Forn en Andrath",
    "Cirith Gorgor",
    "Cirith Ninniach",
    "Cirith Thoronath",
    "Cirith Ungol",
    "Citadel of Stars",
    "City of the Corsairs",
    "Cloudyhead",
    "Cobas Haven",
    "Côf Belfalas",
    "Coldfells",
    "Combe",
    "Cormallen",
    "Corollairë",
    "Coron Oiolairë",
    "Country Round",
    "Court of the Fountain",
    "Crack of Doom",
    "Cracks of Doom",
    "Crickhollow",
    "Crissaegrim",
    "Cristhorn",
    "Cross-roads",
    "Crossings of Teiglin",
    "Cuiviénen",
    "Cûl Bîn",
    "Cûl Veleg",
    "Cûm-nan-Arasaith",
    "Dagorlad",
    "Dale",
    "Dark Door",
    "Dark Gate",
    "Dark Land",
    "Dark Lands",
    "Dark Mountains",
    "Dark Tower",
    "Dead Marshes",
    "Deadmen's Dike",
    "Death Down",
    "Deathless Lands",
    "Deephallow",
    "Deeping Coomb",
    "Deeping Stream",
    "Deeping Wall",
    "Deeping-road",
    "Deeping",
    "Deer's Leap",
    "Deldúwath",
    "Derndingle",
    "Desert of Lostladen",
    "Desolation of Smaug",
    "Desolation of the Morannon",
    "Dimbar",
    "Dimholt",
    "Dimrill Dale",
    "Dimrill Gate",
    "Dimrill Stair",
    "Dimrost",
    "Dingle",
    "Dol Amroth",
    "Dol Baran",
    "Dol Guldur",
    "Dol Tarlang",
    "Dome of Stars",
    "Doors of Durin",
    "Doors of Night",
    "Dor Caranthir",
    "Dor Daedeloth",
    "Dor Daidelos",
    "Dor Dínen",
    "Dor Firn-i-Guinar",
    "Dor-Cúarthol",
    "Dor-en-Ernil",
    "Dor-lómin",
    "Dor-Nu-Fauglith",
    "Doriath",
    "Dorthonion",
    "Dorwinion",
    "Downlands",
    "Drengist",
    "Drowns",
    "Drúadan Forest",
    "Drúwaith Iaur",
    "Dry River",
    "Duilwen",
    "Dungortheb",
    "Dúnharg",
    "Dunharrow",
    "Dunland",
    "Durin's Bridge",
    "Durin's Tower",
    "Durthang",
    "Dwaling",
    "Dwarf-Road",
    "Dwarrowdelf",
    "Dwimorberg",
    "Dwimordene",
    "Eä",
    "Eagles' Eyrie",
    "East Beleriand",
    "East Bight",
    "East Emnet",
    "East Farthing",
    "East Lórien",
    "East March",
    "East Road",
    "East Wall of Rohan",
    "East-gate",
    "East-lands",
    "Eastern Eriador",
    "Eastfarthing",
    "Eastfold",
    "Eastwood",
    "Echad i Sedryn",
    "Echoing Hills",
    "Echoriath",
    "Edge of the Wild",
    "Edhellond",
    "Edoras",
    "Egladil",
    "Eglador",
    "Eglamar",
    "Eglarest",
    "Eilenach",
    "Eilenaer",
    "Eithel Ivrin",
    "Eithel Nínui",
    "Eithel Sirion",
    "Ekkaia",
    "Eldalondë the Green",
    "Eldamar",
    "Elennanórê",
    "Elerrína",
    "Elostirion",
    "Elros' Tower",
    "Elvenhome",
    "Elwing's tower",
    "Emerië",
    "Emyn Arnen",
    "Emyn Beraid",
    "Emyn Duir",
    "Emyn Eglain",
    "Emyn Muil",
    "Emyn Uial",
    "Emyn-nu-Fuin",
    "Enchanted Isles",
    "Enchanted River",
    "Encircling Mountains",
    "Encircling Sea",
    "Endless Stair",
    "Endor",
    "Ened",
    "Enedwaith",
    "Entwade",
    "Entwash Vale",
    "Entwood",
    "Éothéod",
    "Ephel Brandir",
    "Ephel Dúath",
    "Erebor",
    "Erech",
    "Ered Engrin",
    "Ered Gorgoroth",
    "Ered Lindon",
    "Ered Lithui",
    "Ered Lómin",
    "Ered Mithrin",
    "Ered Nimrais",
    "Ered Wethrin",
    "Eregion",
    "Erelas",
    "Erendis",
    "Eriador",
    "Erui",
    "Eryn Fuir",
    "Eryn Galen",
    "Eryn Vorn",
    "Esgalduin",
    "Esgaroth",
    "Estolad",
    "Ethir Anduin",
    "Ethraid Engrin",
    "Ethring",
    "Ettendales",
    "Ettenmoors",
    "Evereven",
    "Everholt",
    "Evernight",
    "Ezellohar",
    "Falas",
    "Falls of Esgalduin",
    "Falls of Irvin",
    "Falls of Rauros",
    "Falls of Sirion",
    "Fangorn Forest",
    "Fanuidhol",
    "Far Downs",
    "Far Harad",
    "Far Shore",
    "Far West",
    "Faskala-númen",
    "Faskalan",
    "Fen Hollen",
    "Fen of Serech",
    "Fenmarch",
    "Fens of Serech",
    "Fens of Sirion",
    "Ferry Lane",
    "Field of Celebrant",
    "Field of Cormallen",
    "Fingolfin's Cairn",
    "Firien Wood",
    "Firienholt",
    "First Deep",
    "First Hall",
    "Firth of Drengist",
    "Firth of Rómenna",
    "Foen",
    "Folde",
    "Ford of Brithiach",
    "Ford of Bruinen",
    "Ford of Stones",
    "Fords of Isen",
    "Forest Gate",
    "Forest of Brethil",
    "Forest of Neldoreth",
    "Forest of Region",
    "Forest ofNeldoreth",
    "Forest River",
    "Forest Road",
    "Forgotten Villages",
    "Forlindon",
    "Forlond",
    "Formenos",
    "Fornarthan",
    "Fornost Erain",
    "Forochel",
    "Forodwaith",
    "Forostar",
    "Forsaken Inn",
    "Fôs' Almir",
    "Fountain of Tinúviel",
    "Fox Downs",
    "Framsburg",
    "Frogmorton",
    "Front Gate",
    "Front Porch",
    "Gabilgathod",
    "Gamwich",
    "Gap of Calenardhon",
    "Gap of Rohan",
    "Gardens of Lórien",
    "Gate of the Dead",
    "Gate of the Noldor",
    "Gate Stream",
    "Gates of Morning",
    "Gates of Sirion",
    "Gelion",
    "Gilrain",
    "Ginglith",
    "Girdle of Arda",
    "Girdle of Melian",
    "Girdley Island",
    "Gladden Fields",
    "Gladden River",
    "Glanduin",
    "Glanhír",
    "Glithui",
    "Glittering Caves",
    "Goblin Gate",
    "Goblin-gate",
    "Goblin-town",
    "Golden Gates",
    "Golden Wood",
    "Gollum's Lake",
    "Gondolin",
    "Gondor",
    "Gorbelgod",
    "Gorge of Aglon",
    "Gorgoroth",
    "great East Road",
    "Great Fens",
    "Great Gulf",
    "Great Hall of Thráin",
    "Great Lakes",
    "Great Lands",
    "Great Mound",
    "Great Plains",
    "Great Rift",
    "Great River",
    "Great Shelf",
    "Great Smials",
    "Great Southern Forests",
    "Great West Road",
    "Great Willow",
    "Greater Gelion",
    "Green Dragon Inn",
    "Green Dragon",
    "Green Fields",
    "Green Hill Country",
    "Green Hills",
    "Greenfields",
    "Greenholm",
    "Greenway",
    "Greenwood the Great",
    "Grey Havens",
    "Grey Mountains",
    "Grey Wood",
    "Greyflood",
    "Greylin",
    "Grinding Ice",
    "Grindwall",
    "Gruir",
    "Guarded Plain",
    "Gulf of Lhûn",
    "Gundabad",
    "Hadhodrond",
    "Haerast",
    "Haeren",
    "Halifirien",
    "Hall of Brodda",
    "Hall of Fire",
    "Halls of Aulë",
    "Halls of Durin",
    "Halls of Mandos",
    "Hanstovánen",
    "Harad Road",
    "Harad",
    "Hardbottle",
    "Harlindon",
    "Harlond",
    "Harondor",
    "Harrowdale",
    "Haudh in Gwanûr",
    "Haudh-en-Elleth",
    "Haudh-en-Ndengin",
    "Haudh-en-Nirnaeth",
    "Haunted Mountain",
    "Haunted Pass",
    "Haven of the Eldar",
    "Haven of the Swans",
    "Haven of Umbar",
    "Havens of Mithlond",
    "Havens of Sirion",
    "Hay Gate",
    "Haysend",
    "Heats of the South",
    "Helcaraxë",
    "Helm's Deep",
    "Helm's Dike",
    "Helm's Gate",
    "Henneth Annûn",
    "Hidden Ferries",
    "Hidden Way",
    "High Court",
    "High Faroth",
    "High Hay",
    "High Pass",
    "Hildórien",
    "Hill of Awe",
    "Hill of Guard",
    "Hill of Hearing",
    "Hill of Himring",
    "Hill of Ilmarin",
    "Hill of Oromet",
    "Hill of Seeing",
    "Hill of Spies",
    "Hill of the Ear",
    "Hill of the Eye",
    "Hills of Eglamar",
    "Hills of Evendim",
    "Hills of Scary",
    "Himlad",
    "Himring",
    "Hírilorn",
    "Hisilómë",
    "Hithaeglir",
    "Hither Lands",
    "Hither Shore",
    "Hithlum",
    "Hoarwell",
    "Hobbit-hole",
    "Hobbiton Hill",
    "Hobbiton Road",
    "Hobbiton",
    "Hollin Gate",
    "Hollin Ridge",
    "Hollin",
    "Hornburg",
    "Hornrock",
    "House of Oromë",
    "House of the Dead",
    "House of the Hundred Chimneys",
    "House of the Kings",
    "House of the Stewards",
    "House of Tulkas",
    "House ofNienna",
    "Houses of Healing",
    "Huts of the raft-elves",
    "Hyarastorni",
    "Hyarmentir",
    "Hyarnustar",
    "Hyarrostar",
    "i Drann",
    "Iant Iaur",
    "Ice of the North",
    "Icebay of Forochel",
    "Idril's secret way",
    "Illuin",
    "Ilmarin",
    "Ilmen",
    "Imlad Morgul",
    "Imladris",
    "Imloth Melui",
    "Imrath Gondraith",
    "Inland Sea of Helcar",
    "Inland Sea",
    "Inn of the Prancing Pony",
    "Inner Seas",
    "Írensaga",
    "Iron Fortress",
    "Iron Hills",
    "Iron Mountains",
    "Isen",
    "Isengard",
    "Isenmouthe",
    "Ishmalog",
    "Isle of Almaren",
    "Isle of Balar",
    "Isle of Elenna",
    "Isle of Eressëa",
    "Isle of Meneltarma",
    "Isle of Werewolves",
    "Isles of the West",
    "Ithilien",
    "Ivrin's Well",
    "Ivrin",
    "Ivy Bush",
    "Kalormë",
    "Karningul",
    "Kelos",
    "Khand",
    "Khazad-dûm",
    "Kheled-zâram",
    "Kibil-nâla",
    "King's Court",
    "King's House",
    "Kingdom of the South",
    "Kingdom under the Mountain",
    "Kings' Norbury",
    "Kingsland",
    "Kiril",
    "Kirith Ungol",
    "Kôr",
    "Kortirion",
    "Ladros",
    "Lake Helevorn",
    "Lake Mithrim",
    "Lake Nenuial",
    "Lake Town",
    "Lake-town",
    "LakeNísinen",
    "Lamedon",
    "Lammoth",
    "Lampwrights' Street",
    "Land Beyond",
    "Land of Bow-Helm",
    "Land of the Dead that Live",
    "Land of the Necromancer",
    "Land of the Sun",
    "Lands Under the Wave",
    "Lands Without",
    "Langflood",
    "Langstrand",
    "Lanthir Lamath",
    "Last Bridge",
    "Last Desert",
    "Last Homely House",
    "Last Mountain",
    "Last Shore",
    "Laurelindórenan",
    "Lebennin",
    "Lhûn",
    "Linaewen",
    "Lindon",
    "Lindórinan",
    "Linhir",
    "Lisgardh",
    "Lithlad",
    "Little Delving",
    "Little River Gelion",
    "Lockholes",
    "Loeg Ningloron",
    "Lond Daer Enedh",
    "Lone-lands",
    "Lonely Isle",
    "Lonely Mountain",
    "Long Cleeve",
    "Long Lake",
    "Long Marshes",
    "Long the Wall",
    "Longbottom",
    "Lórellin",
    "Lórien",
    "Lórinand",
    "Losgar",
    "Lossarnach",
    "Lost Isle",
    "Lothlann",
    "Lothlorièn",
    "Lothlórien",
    "Loudwater",
    "Lower Halls",
    "Lugbúrz",
    "Lune",
    "Luthany",
    "Luvailin",
    "Maggot's Farm",
    "Maggot's Lane",
    "Maglor's Gap",
    "Máhanaxar",
    "Mahanaxar",
    "Mansions of Aulë",
    "Mar-nu-Falmar",
    "March of Maedhros",
    "Marish",
    "Market-pool",
    "Marshes of Nevrast",
    "Meduseld",
    "Men-i-Naugrim",
    "Menegroth",
    "Meneltarma",
    "Mere of Dead Faces",
    "Meres of Twilight",
    "Merethrond",
    "Mering Stream",
    "Methed-en-glad",
    "Methedras",
    "Michel Delving",
    "Middle-earth",
    "Midgewater Marshes",
    "Min-Rimmon",
    "Minas Anor",
    "Minas Ithil",
    "Minas Morgul",
    "Minas Tirith",
    "Mindon Eldaliéva",
    "Mines of Moria",
    "Minhiriath",
    "Mirkwood",
    "Mirrormere",
    "Misty Mountains",
    "Mithe Steps",
    "Mithe",
    "Mitheithel",
    "Mithlond",
    "Mithrim",
    "Mittalmar",
    "Moors of the Neweglu",
    "Moors of the Nibin-noeg",
    "Morannon",
    "Mordor",
    "Morgai",
    "Morgul Pass",
    "Morgul-road",
    "Moria",
    "Mornan",
    "Mound of Avarice",
    "Mound of Dunlendings",
    "Mound of Riders",
    "Mounds of Mundburg",
    "Mount Dolmed",
    "Mount Doom",
    "Mount Everwhite",
    "Mount Fang",
    "Mount Gram",
    "Mount Gundabad",
    "Mount Mindolluin",
    "Mount of the Pine Tree",
    "Mount Rerir",
    "Mount Taras",
    "Mountain of Fire",
    "Mountains of Aman",
    "Mountains of Angmar",
    "Mountains of Lune",
    "Mountains of Mirkwood",
    "Mountains of Mithrim",
    "Mountains of Shadow",
    "Mountains of Terror",
    "Mountains of the East",
    "MountMindolluin",
    "Mouths of Anduin",
    "Mouths of Entwash",
    "Mouths of Sirion",
    "Mundburg",
    "N/A",
    "Nameless Land",
    "Nan Curunír",
    "Nan Dungortheb",
    "Nan Elmoth",
    "Nan-tathren",
    "Nanduhirrion",
    "Narchost",
    "Nardol",
    "Nargothrond",
    "Narrows of the Forest",
    "Near Harad",
    "Needlehole",
    "Nen Echui",
    "Nen Girith",
    "Nen Hithoel",
    "Nen Lalaith",
    "Nenuial",
    "Nether Dark",
    "Nevrast",
    "New Haven",
    "New Lands",
    "Newbury",
    "Nimbrethil",
    "Nîn-in-Eilph",
    "Nindalf",
    "Nindamos",
    "Ninglor",
    "Nísimaldar",
    "Nivrim",
    "Nobottle",
    "Nogrod",
    "Noirinan",
    "Noman-lands",
    "Norbury",
    "North Cape",
    "North Downs",
    "North Farthing",
    "North Gate",
    "North Ithilien",
    "North Kingdom",
    "North Marches",
    "North Moors",
    "North Road of Ithilien",
    "North Road",
    "North Stair",
    "North Undeep",
    "Northerland",
    "Northern Dark",
    "Northern Waste",
    "Novrod",
    "Núath Woods of",
    "Núath",
    "Númendor",
    "Númenor",
    "Nunduinë",
    "Nurn",
    "Oatbarton",
    "Obel Halad",
    "Ocean",
    "Oiolossë",
    "Oiomúrë",
    "Old Bridge",
    "Old Ford",
    "Old Forest Road",
    "Old Forest",
    "Old Grange",
    "Old Guesthouse",
    "Old Mill",
    "Old Púkel land",
    "Old Road",
    "Old South Road",
    "Old Winyards",
    "Old World",
    "Ondolindë",
    "Ondoluncanando",
    "Ondonórë",
    "Ondosto",
    "Onodló",
    "Orc-holds",
    "Orfalch Echor",
    "Ormal",
    "Orocarni",
    "Orod-na-Thôn",
    "Orodruin",
    "Oromet",
    "Orrostar",
    "Orthanc",
    "Osgiliath",
    "Ossiriand",
    "Ost-in-Edhil",
    "Otherworld",
    "Outer Dark or Outer Darkness",
    "Outer Lands",
    "Outer Sea",
    "Outlands",
    "Overbourn Marshes",
    "Overbourn",
    "Overhill",
    "Palisor",
    "Parth Celebrant",
    "Parth Galen",
    "Party Field",
    "Pass of Aglon",
    "Pass of Anach",
    "Pastures of Yavanna",
    "Paths of the Dead",
    "Pelargir",
    "Pelennor Fields",
    "Pelennor",
    "Pelóri",
    "Phûrunargian",
    "Pillars of the King",
    "Pincup",
    "Pine-mountain",
    "Pinnath Gelin",
    "Place of the Fountain",
    "Plateau of Gorgoroth",
    "Pool of Bywater",
    "Pool-side",
    "Pools of Ivrin",
    "Prancing thePony",
    "Qerkaringa",
    "Quarry",
    "Radhrim",
    "Rainbow Cleft",
    "Ramdal",
    "Rammas Echor",
    "Ras Mewrim",
    "Ras Morthil",
    "Rath Celerdain",
    "Rath Dínen",
    "Rathlóriel",
    "Rauros",
    "Ravenhill",
    "Ravines of Teiglin",
    "Realm of Angmar",
    "Redhorn PassGate",
    "Redhorn",
    "Redwater",
    "Region of Everlasting Cold",
    "Region",
    "Regions of the Shire",
    "Reunited Kingdom",
    "Rhimdath",
    "Rhosgobel",
    "Rhovanion",
    "Rhudaur",
    "Rhûn",
    "Ring of Doom",
    "Ring of Isengard",
    "Ringil",
    "Rivendell",
    "River Entwash",
    "River Gwathló",
    "River Harnen",
    "River Langwell",
    "River Lefnui",
    "River Legolin",
    "River Lithir",
    "River Malduin",
    "River Morthond",
    "River of Anduin",
    "River of Aros",
    "River of Ascar",
    "River Running",
    "RiverMindeb",
    "RiverMorgulduin",
    "RiverNarog",
    "RiverNenning",
    "RiverNimrodel",
    "RiverPoros",
    "RiverRingló",
    "RiverRingwil",
    "RiverRivil",
    "RiverShirebourn",
    "RiverSilverlode",
    "RiverSiril",
    "RiverSirion",
    "RiverSirith",
    "RiverSnowbourn",
    "RiverTaeglin",
    "Rivil's Well",
    "Rochand",
    "Rómenna",
    "Rûnaer",
    "Rushdown",
    "Rushock Bog",
    "Rushy",
    "Sammath Naur",
    "Sandyman's Mill",
    "Sarn Athrad",
    "Sarn Ford",
    "Sarn Gebir",
    "Sauron's Isle",
    "Sauron's Road",
    "Sauron's Temple",
    "Scary",
    "Sea of Helcar",
    "Sea of Núrnen",
    "Sea of Rhûn",
    "Sea of Ringil",
    "Sea ofRingil",
    "Sea-ward Tower",
    "Seat of Hearing",
    "Seat of Seeing",
    "Second Hall",
    "Serni",
    "Seven Gates of Gondolin",
    "Seventh Level",
    "Shadowmere",
    "Shadowy Isles",
    "Shadowy Mountains",
    "Shadowy Seas",
    "Shadowy Spring",
    "Sharabhund",
    "Shathûr",
    "Shelob's Lair",
    "Side-door",
    "Silvertine",
    "Sindanórie",
    "Sîr Ninglor",
    "Sirannon",
    "Slag-hills",
    "Sorontil",
    "South Downs",
    "South EriadorRoad",
    "South Farthing",
    "South Gondor",
    "South GondorRoad",
    "South Ithilien",
    "South Kingdom",
    "South Lane",
    "South Undeep",
    "Southward Road",
    "Spider's Ring",
    "Staddle",
    "Stair Falls",
    "Stair of the Hold",
    "Standelf",
    "Starkhorn",
    "Steward's Door",
    "Stock Road",
    "Stock",
    "Stockbrook",
    "Stonewain Valley",
    "Stoningland",
    "Straight Road",
    "Straight Stair",
    "Straits of the World",
    "Sundering Seas",
    "Sunlands",
    "Sunlendings",
    "Sûthburg",
    "Sûza",
    "Swanfleet",
    "Talath Dirnen",
    "Talath Rhûnen",
    "Taniquetil",
    "Tanyasalpë",
    "Tar-Minastir",
    "Tarlang's Neck",
    "Tarmasundar",
    "Tarn Aeluin",
    "Tarnost",
    "Tasarinan",
    "Taur e-Ndaedelos",
    "Taur-en-Faroth",
    "Taur-im-Duinath",
    "Taur-na-Foen",
    "Taur-Na-Neldor",
    "Taur-nu-Fuin",
    "Tauremorna",
    "Tauremornalómë",
    "Tavrobel",
    "Temple of Sauron",
    "Thangorodrim",
    "Tharbad",
    "Thargelion",
    "The Bounds",
    "The Forsaken Inn",
    "The Great Mill",
    "the Hedge",
    "the Hill",
    "The Marish",
    "The Misty Mountains",
    "The River Thalos",
    "The Rivers and Beacon-Hills of Gondor",
    "The Shire",
    "The Void",
    "The Yale",
    "TheMark",
    "theNaith",
    "theSea",
    "theShire",
    "Thistle Brook",
    "Thorin's Halls",
    "Thousand Caves",
    "Three-Farthing Stone",
    "Thrihyrne",
    "Tighfield",
    "Timeless Halls",
    "Tindrock",
    "Tirion",
    "Tirith Aear",
    "Tol Brandir",
    "Tol Eressëa",
    "Tol Fuin",
    "Tol Galen",
    "Tol Morwen",
    "Tol Sirion",
    "Tol Uinen",
    "Tol-in-Gaurhoth",
    "Tolfalas",
    "Tomb of the Kings",
    "Tongue",
    "Tookbank",
    "Tookland",
    "Torech Ungol",
    "Tower Hills",
    "Tower of Cirith Ungol",
    "Tower of Ecthelion",
    "Tower of Ingwë",
    "Tower of the King",
    "Tower of the Stone",
    "Towers of the Teeth",
    "Town Hole",
    "Treebeard's Hill",
    "Treegarth of Orthanc",
    "Troll's Cave",
    "Trollshaws",
    "Tuckborough",
    "Tumhalad",
    "Tumladen of Gondolin",
    "Tumladen of Gondor",
    "Tumladen",
    "Tumunzahar",
    "Túna",
    "Twenty-First Hall of the North-end",
    "Twilight Meres",
    "Two Watchers",
    "Tyrn Gorthad",
    "Udul",
    "Udûn of Mordor",
    "Udûn",
    "Ulmonan",
    "Umbar",
    "Umboth-muilin",
    "Undeeps",
    "Under-Hill",
    "Under-way",
    "Undergate",
    "Underharrow",
    "Underhill",
    "Undertowers",
    "Undying Lands",
    "Ungoliant's Lair",
    "Upbourn",
    "Uttermost West",
    "Utumno",
    "Vaiya",
    "Valandor",
    "Vale of Sirion",
    "Valimar",
    "Valinor",
    "Valmar",
    "Verna",
    "Vinyalondë",
    "Vinyamar",
    "Vista",
    "Void",
    "Waking Water",
    "Wall's End",
    "Walls of Moria",
    "Walls of the Night",
    "Walls of the Sun",
    "Walls of the World",
    "Wargs' Clearing",
    "Waste",
    "Watchwood",
    "Water of Awakening",
    "Water-valley",
    "Way of Escape",
    "Way of Running Waters",
    "Waymeet",
    "Weather Hills",
    "Weathertop",
    "Wellinghall",
    "Wells of Ivrin",
    "Wells of Varda",
    "West Beleriand",
    "West of the World",
    "West Pass",
    "West Road",
    "West-door",
    "West-gate of Bree",
    "West-gate of Moria",
    "West-mark",
    "Westemnet",
    "Westermanton",
    "Western Sea",
    "Western Shore",
    "Westernesse",
    "Westfarthing",
    "Westfold Vale",
    "Westfold",
    "Westlands",
    "Westmarch",
    "Wetwang",
    "Whispering Wood",
    "White Downs",
    "White House of Erendis",
    "White Mountain",
    "White Mountains",
    "White Tower",
    "White Towers",
    "Whitfurrows",
    "Whitwell",
    "Wild Wood",
    "Wilderland",
    "Willowbottom",
    "Winding Stair",
    "Windle-reach",
    "Window of the West",
    "Window-Curtain",
    "Withered Heath",
    "Withered Wold",
    "Withy-path",
    "Withy-weir",
    "Withywindle River",
    "Withywindle Valley",
    "Wizard's Isle",
    "Wizard's Vale",
    "Wold of Rohan",
    "Wood of Anwar",
    "Woodhall",
    "Woodland Realm",
    "Woods of Oromë",
    "Woody End",
    "Yellow Mountains",
    "Yôzâyan",
    "Zirakzigil"
  ])
end
