defmodule Faker.Vine.En do
  import Faker, only: [sampler: 2]

  @moduledoc """
  Functions for generating Vine related data in English
  """

  @doc """
  Returns a Vine strain string

  ## Examples

      iex> Faker.Vine.En.strain()
      "Lola"
      iex> Faker.Vine.En.strain()
      "Len De L'el"
      iex> Faker.Vine.En.strain()
      "Villard Blanc"
      iex> Faker.Vine.En.strain()
      "Bouchales"
  """
  @spec strain() :: String.t()
  sampler(:strain, [
    "Abouriou",
    "Afus Ali",
    "Aleatico",
    "Alicante Ganzin",
    "Alicante Henri Bouschet",
    "Aligote",
    "Aramon Du Gard",
    "Aramon Noir",
    "Arinarnoa",
    "Arnold Chevalier 3401",
    "Aromatica",
    "Arriloba",
    "Aubun",
    "Augster Blau",
    "Auldana 1",
    "Aurore",
    "Auxerrois",
    "Avant Garde",
    "Babeasca Neagra",
    "Baco Blanc",
    "Baco Noir",
    "Barbableu",
    "Baroque",
    "Barral Negret",
    "Batard De Sauternes",
    "Bequignol Blanc",
    "Bertille Seyve 413",
    "Bertille Seyve 450",
    "Bertille Seyve 822",
    "Bertille Seyve 872",
    "Bertille Seyve 1838",
    "Bertille Seyve 2833",
    "Bianco D'alessano",
    "Black Prince",
    "Black Rose",
    "Bon Roussillon",
    "Bouchales",
    "Bouillenc",
    "Bouschet Petit",
    "Bushkanskii Krasnyi",
    "Cabernet Franc",
    "Cabernet Sauvignon",
    "Canari Noir",
    "Canner Seedless",
    "Cardinal",
    "Carignan Noir",
    "Carmenere",
    "Castel  6239",
    "Castel 20415",
    "Cazalet",
    "Celine",
    "Chambourcin",
    "Chancellor",
    "Chaouch Blanc",
    "Chardonnay Blanc",
    "Chasselas Blanc",
    "Cinsaut",
    "Clinton",
    "Contassot",
    "Cot",
    "Cot De Cheragas",
    "Couderc 2",
    "Couderc 3",
    "Couderc 4",
    "Couderc 7",
    "Couderc 8",
    "Couderc 15",
    "Couderc 104-46",
    "Couderc 128-29",
    "Couderc 162-5",
    "Couderc 252-14",
    "Couderc 267-27",
    "Couderc 299-17",
    "Couderc 4308",
    "Couderc 7104",
    "Couderc Noir",
    "Counoise",
    "Courbu Blanc",
    "Criolla Negra",
    "Crouchen",
    "Csaba Gyoengye",
    "De Chaunac",
    "Delizia Di Vaprio",
    "Dimyat",
    "Doina",
    "Dolcetto",
    "Douriou",
    "Duc Petit",
    "Durif",
    "Egiodola",
    "Elbling Weiss",
    "Elvira",
    "Emperor",
    "Estellat",
    "Etoile Ii",
    "Fer",
    "Feteasca Alba",
    "Feteasca Regala",
    "Flot D'or",
    "Flot Rouge",
    "Folle Blanche",
    "Friulano",
    "Furmint",
    "Gaillard 194",
    "Gamay Noir",
    "Gamay Teinturier Freaux",
    "Ganson",
    "Garnacha Tinta",
    "Gascon",
    "Geilweilerhof Ga-52-42",
    "Geilweilerhof Ga-58-14",
    "Geilweilerhof V. 3125",
    "Gewuerztraminer",
    "Gloire De Seibel",
    "Goyura",
    "Graciano",
    "Grand Noir",
    "Grasa De Cotnari",
    "Grolleau Noir",
    "Guzal Kara",
    "Heunisch Weiss",
    "Himrod",
    "Honigler",
    "Invulnerable",
    "Irsai Oliver",
    "Isabella",
    "Italia",
    "Jacquere",
    "Jacquez",
    "Jaoumet",
    "Jurancon Blanc",
    "Karmrahyut",
    "Kerner",
    "Kishmish Chernyi",
    "Knipperle",
    "Kodru",
    "Korinthiaki",
    "La Crosse",
    "Lagrein",
    "Lattuario Nero",
    "Lauzet",
    "Len De L'el",
    "Leon Millot",
    "Lercat",
    "Liliorila",
    "Listan Prieto",
    "Lola",
    "Madame Castel",
    "Madeleine Angevine",
    "Madone",
    "Magaracha Rannii",
    "Malbec Precoce",
    "Malegue 469-9",
    "Malegue 1157-1",
    "Malegue 1459-1",
    "Malegue 2049-3",
    "Malegue 2094-3",
    "Malpe",
    "Mancin",
    "Manseng Gros Blanc",
    "Manseng Vert",
    "Marechal Foch",
    "Marsanne",
    "Mauzac Blanc",
    "Melon",
    "Merced",
    "Merille",
    "Merlot Blanc",
    "Merlot Noir",
    "Meslier Petit",
    "Meslier Saint Francois",
    "Messidor",
    "Milgranet",
    "Mirifica",
    "Misket Cherven",
    "Monastrell",
    "Montera",
    "Montils",
    "Morenoa",
    "Morio Muskat",
    "Mueller Thurgau Weiss",
    "Muscadelle",
    "Muscat A Petits Grains Blancs",
    "Muscat Fleur D'oranger",
    "Muscat Hamburg",
    "Muscat Of Alexandria",
    "Muska",
    "Muskat Susanna",
    "Negru Moale",
    "Noual",
    "Nouveau Bayard",
    "Oberlin 716",
    "Oberlin 782",
    "Odola",
    "Oiseau Bleu",
    "Oiseau Rouge",
    "Ondenc",
    "Onitskanskii Belyi",
    "Orion",
    "Ortrugo",
    "Pajolera",
    "Palava",
    "Palen",
    "Pannonia Kincse",
    "Pardotte",
    "Parellada",
    "Pate Noir",
    "Perdauque",
    "Perlette",
    "Perlette Loose",
    "Pineau D'aunis",
    "Pinot Gris",
    "Pinot Meunier",
    "Pinot Noir",
    "Piquepoul Noir",
    "Pirobella",
    "Plant Droit",
    "Plant Du Metayer",
    "Plantet",
    "Pollux",
    "Porche",
    "Portugieser Blau",
    "Pourpre",
    "President",
    "Primitivo",
    "Prokupac",
    "Queen",
    "Raffiat De Moncade",
    "Redora",
    "Regent",
    "Reichensteiner",
    "Reliance",
    "Riesling Weiss",
    "Rkatsiteli",
    "Roi Des Noirs",
    "Rubired",
    "Saint Pierre Dore",
    "Saperavi",
    "Sauvignon Blanc",
    "Scheurebe",
    "Seibel 2",
    "Seibel 867",
    "Seibel 880",
    "Seibel 2010",
    "Seibel 4464",
    "Seibel 4615",
    "Seibel 4633",
    "Seibel 4644",
    "Seibel 4648",
    "Seibel 4681",
    "Seibel 4707",
    "Seibel 4709",
    "Seibel 4762",
    "Seibel 4955",
    "Seibel 4964",
    "Seibel 4989",
    "Seibel 4990",
    "Seibel 4991",
    "Seibel 4995",
    "Seibel 5061",
    "Seibel 5163",
    "Seibel 5188",
    "Seibel 5191",
    "Seibel 5202",
    "Seibel 5204",
    "Seibel 5231",
    "Seibel 5259",
    "Seibel 5296",
    "Seibel 5431",
    "Seibel 5437",
    "Seibel 5744",
    "Seibel 5813",
    "Seibel 5912",
    "Seibel 5915",
    "Seibel 5916",
    "Seibel 6086",
    "Seibel 6131",
    "Seibel 6468",
    "Seibel 6740",
    "Seibel 7056",
    "Seibel 7787",
    "Semebat",
    "Semillon",
    "Silvaner Gruen",
    "Sonora",
    "St. Pepin",
    "Staufer",
    "Suavis",
    "Sultanina",
    "Suruchenskii Belyi",
    "Syrah",
    "Tannat",
    "Taranta",
    "Teinturier",
    "Teroldego",
    "Terret Noir",
    "Tinta Carvalha",
    "Touriga Nacional",
    "Trebbiano Toscano",
    "Trousseau Gris",
    "Valdiguie",
    "Valiant",
    "Veltliner Gruen",
    "Verdelet",
    "Verdot Petit",
    "Vermentino",
    "Vert Dore",
    "Vidal Blanc",
    "Vignoles",
    "Villard Blanc",
    "Vitis Arizonica Engelmann",
    "Vitis Betulifolia Diels Et Gilg",
    "Vitis Champinii Planchon",
    "Vitis Cinerea Engelmann Var. Cinerea",
    "Vitis Cordifolia Michaux",
    "Vitis Girdiana Munson",
    "Vitis Piasezkii Maximowicz",
    "Vitis Riparia Michaux",
    "Vitis Romanetii Romanet Du Caillaud",
    "Vitis Rupestris Scheele",
    "Vitis Thunbergii Siebold Et Zuccarina",
    "Vitis Yeshanensis Chen",
    "Viura",
    "Welschriesling",
    "Zaomeigui",
    "Zaranda",
    "Zelen",
    "Souvignier Gris"
  ])
end
